services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # Domain layer
    #

    Rainbow\Discounts\Domain\DiscountService: ~

    #
    # Application layer
    #

    Rainbow\Discounts\Application\Controllers\:
        resource: ../src/Application/Controllers/*
        public: true

    Rainbow\Discounts\Application\Framework\ExceptionListener: ~

    Money\Currencies:
        class: Money\Currencies\ISOCurrencies
    Money\Parser\DecimalMoneyParser: ~
    Money\Formatter\DecimalMoneyFormatter: ~

    Rainbow\Discounts\Application\OrderParser: ~
    Rainbow\Discounts\Application\OrderSerializer: ~

    #
    # Infrastructure layer
    #

    Rainbow\Discounts\Domain\ProductRepository:
        class: Rainbow\Discounts\Infrastructure\JsonProductRepository
        arguments:
            - "%kernel.project_dir%/data/products.json"

    Rainbow\Discounts\Domain\DiscountRuleRepository:
        class: Rainbow\Discounts\Infrastructure\HardcodedDiscountRuleRepository
